Untabify script

diff --git a/BxBoostInstaller/boost_installer b/BxBoostInstaller/boost_installer
--- a/BxBoostInstaller/boost_installer
+++ b/BxBoostInstaller/boost_installer
@@ -249,16 +249,16 @@ function boost_installer_install()
     bxiw_message "info" "BOOST source directory is       : '${_boost_source_dir}'"
     if [ ! -d ${_boost_source_dir} ]; then
         bxiw_message "info" "Unpacking source directory..."
-	tar xjzf ${bxiw_cache_dir}/${_boost_tarball}
-	if [ $? -ne 0 ]; then
-	    bxiw_message "error" "Source directory has not been unpacked."
-	    cd ${_boost_opwd}
-	    return 1
-	else
-	    bxiw_message "info" "Source directory has been unpacked."
-	fi
+        tar xjzf ${bxiw_cache_dir}/${_boost_tarball}
+        if [ $? -ne 0 ]; then
+            bxiw_message "error" "Source directory has not been unpacked."
+            cd ${_boost_opwd}
+            return 1
+        else
+            bxiw_message "info" "Source directory has been unpacked."
+        fi
     else
-	bxiw_message "info" "Source directory was already unpacked."
+        bxiw_message "info" "Source directory was already unpacked."
     fi
 
     bxiw_message "info" "BOOST build directory is        : '${bxiw_build_dir}'"
@@ -266,11 +266,11 @@ function boost_installer_install()
     bxiw_message "info" "BOOST installation directory is : '${bxiw_install_dir}'"
 
     if [ ! -f ${bxiw_build_dir}/bootstrap.sh ]; then
-	bxiw_message "info" "Copying the source directory in the build directory..."
-	cp -a ${_boost_source_dir}/* ${bxiw_build_dir}/
+        bxiw_message "info" "Copying the source directory in the build directory..."
+        cp -a ${_boost_source_dir}/* ${bxiw_build_dir}/
     else
-	bxiw_message "info" "The source directory is already cloned in the build directory."
-	ls -1 ${bxiw_build_dir}
+        bxiw_message "info" "The source directory is already cloned in the build directory."
+        ls -1 ${bxiw_build_dir}
     fi
 
     cd ${bxiw_build_dir}
@@ -278,116 +278,116 @@ function boost_installer_install()
     # Configuration:
     local _boost_do_config=false
     if [ ! -f ${bxiw_tag_configured} ]; then
-	bxiw_message "info" "BOOST configuration is needed."
-	_boost_do_config=true
+        bxiw_message "info" "BOOST configuration is needed."
+        _boost_do_config=true
     else
-	bxiw_message "info" "BOOST configuration is already done."
-	if [ ${bxiw_do_reconfigure} == true ]; then
-	    bxiw_message "info" "Forcing BOOST reconfiguration..."
-	    _boost_do_configure=true
-	fi
+        bxiw_message "info" "BOOST configuration is already done."
+        if [ ${bxiw_do_reconfigure} == true ]; then
+            bxiw_message "info" "Forcing BOOST reconfiguration..."
+            _boost_do_configure=true
+        fi
     fi
  
     if [ ${_boost_do_config} == true ]; then
-	bxiw_message "info" "BOOST configuration..."
-	./bootstrap.sh \
-	    --with-libraries="${boost_libs}" \
-	    --with-python=$(which python) \
-	    --with-icu \
-	    ${_boost_source_dir}
-	if [ $? -ne 0 ]; then
-	    bxiw_message "error" "BOOST configuration failed!"
-	    cd ${_boost_opwd}
-	    return 1
-	else
-	    touch ${bxiw_tag_configured}
-    	    bxiw_message "info" "BOOST is configured."
-	fi
+        bxiw_message "info" "BOOST configuration..."
+        ./bootstrap.sh \
+            --with-libraries="${boost_libs}" \
+            --with-python=$(which python) \
+            --with-icu \
+            ${_boost_source_dir}
+        if [ $? -ne 0 ]; then
+            bxiw_message "error" "BOOST configuration failed!"
+            cd ${_boost_opwd}
+            return 1
+        else
+            touch ${bxiw_tag_configured}
+            bxiw_message "info" "BOOST is configured."
+        fi
     else
-	bxiw_message "info" "Do not configure BOOST."
+        bxiw_message "info" "Do not configure BOOST."
     fi
 
     # Build:
     local _boost_do_build=false
     if [ ! -f ${bxiw_tag_built} ]; then
-	bxiw_message "info" "BOOST build is needed."
-	_boost_do_build=true
+        bxiw_message "info" "BOOST build is needed."
+        _boost_do_build=true
     else
-	bxiw_message "info" "BOOST build is already done."
-	if [ ${bxiw_do_rebuild} == true ]; then
-	    bxiw_message "info" "Forcing BOOST rebuild..."
-	    _boost_do_build=true
-	fi
+        bxiw_message "info" "BOOST build is already done."
+        if [ ${bxiw_do_rebuild} == true ]; then
+            bxiw_message "info" "Forcing BOOST rebuild..."
+            _boost_do_build=true
+        fi
     fi
 
     if [ ${_boost_do_build} == true ]; then
-	bxiw_message "info" "Building BOOST..."
-	local _boost_nbprocs=${bxiw_nbprocs}
-	if [ ${_boost_nbprocs} -gt 2 ]; then
-	    let _boost_nbprocs=${bxiw_nbprocs}
-	else
-	    _boost_nbprocs=1 
-	fi
-	bxiw_message "info" "#procs = ${_boost_nbprocs}"
-    	./b2 stage
-	if [ $? -ne 0 ]; then
-    	    bxiw_message "error" "BOOST build failed!"
-    	    cd ${_boost_opwd}
-    	    return 1
-	else
-	    touch ${bxiw_tag_built}
-    	    bxiw_message "info" "BOOST is built."
-	fi
+        bxiw_message "info" "Building BOOST..."
+        local _boost_nbprocs=${bxiw_nbprocs}
+        if [ ${_boost_nbprocs} -gt 2 ]; then
+            let _boost_nbprocs=${bxiw_nbprocs}
+        else
+            _boost_nbprocs=1 
+        fi
+        bxiw_message "info" "#procs = ${_boost_nbprocs}"
+        ./b2 stage
+        if [ $? -ne 0 ]; then
+            bxiw_message "error" "BOOST build failed!"
+            cd ${_boost_opwd}
+            return 1
+        else
+            touch ${bxiw_tag_built}
+            bxiw_message "info" "BOOST is built."
+        fi
     else
-	bxiw_message "info" "Do not build BOOST."
+        bxiw_message "info" "Do not build BOOST."
     fi
 
     # Installation:
     local _boost_do_install=false
     if [ ! -f ${bxiw_tag_installed} ]; then
-	bxiw_message "info" "BOOST installation is needed."
-	_boost_do_install=true
+        bxiw_message "info" "BOOST installation is needed."
+        _boost_do_install=true
     else
-	bxiw_message "info" "BOOST installation is already done."
-	if [ ${bxiw_do_reinstall} == true ]; then
-	    _boost_do_install=true
-	    bxiw_message "info" "Forcing BOOST installation..."
-	fi
+        bxiw_message "info" "BOOST installation is already done."
+        if [ ${bxiw_do_reinstall} == true ]; then
+            _boost_do_install=true
+            bxiw_message "info" "Forcing BOOST installation..."
+        fi
     fi
     if [ ${bxiw_no_install} == true ]; then
-	_boost_do_install=false
+        _boost_do_install=false
     fi
 
     if [ ${_boost_do_install} == true ]; then
-	local _boost_do_package=false
-	if [ ${bxiw_with_package} == true ]; then
-	    _boost_do_package=true
-	fi
-	if [ ${_boost_do_package} == true ]; then
-	    if [ "x${bxiw_os_distrib_id}" = "xUbuntu" ]; then
-		bxiw_message "info" "Building a binary package for BOOST..."
-		boost_installer_makedebpack
-	    else
-    		bxiw_message "error" "Cannot pack BOOST for '${bxiw_os_distrib_id}'!"
-    		cd ${_boost_opwd}
-		return 1
-	    fi
-	else
-	    bxiw_message "info" "Installing BOOST..."
-	    ./b2 \
-		--prefix="${bxiw_install_dir}" \
-		install
-	    if [ $? -ne 0 ]; then
-    		bxiw_message "error" "BOOST installation failed!"
-    		cd ${_boost_opwd}
-    		return 1
-	    else
-		touch ${bxiw_tag_installed}
-    		bxiw_message "info" "BOOST is installed."
-	    fi
-	fi
+        local _boost_do_package=false
+        if [ ${bxiw_with_package} == true ]; then
+            _boost_do_package=true
+        fi
+        if [ ${_boost_do_package} == true ]; then
+            if [ "x${bxiw_os_distrib_id}" = "xUbuntu" ]; then
+                bxiw_message "info" "Building a binary package for BOOST..."
+                boost_installer_makedebpack
+            else
+                bxiw_message "error" "Cannot pack BOOST for '${bxiw_os_distrib_id}'!"
+                cd ${_boost_opwd}
+                return 1
+            fi
+        else
+            bxiw_message "info" "Installing BOOST..."
+            ./b2 \
+                --prefix="${bxiw_install_dir}" \
+                install
+            if [ $? -ne 0 ]; then
+                bxiw_message "error" "BOOST installation failed!"
+                cd ${_boost_opwd}
+                return 1
+            else
+                touch ${bxiw_tag_installed}
+                bxiw_message "info" "BOOST is installed."
+            fi
+        fi
     else
-	bxiw_message "info" "Do not install BOOST."
+        bxiw_message "info" "Do not install BOOST."
     fi
     cd ${_boost_opwd}
     return  0
@@ -411,47 +411,47 @@ EOF
     local _boost_do_package=true
     local _boost_pkg_filename="bx${package_name}_${package_version}-${pkg_release}_${_arch}.deb"
     if [ -f ${package_dir}/${_boost_pkg_filename} ]; then
-	echo >&2 "[info] Package '${_boost_pkg_filename}' exists in '${package_dir}'."
-	_boost_do_package=false
+        echo >&2 "[info] Package '${_boost_pkg_filename}' exists in '${package_dir}'."
+        _boost_do_package=false
     fi
     local _boost_requires="\
-		g++ \
-		python libpython2.7 \
-		zlib1g \
-		bzip2 \
-		libxml2 \
-		libicu60 \
-	  "
+                g++ \
+                python libpython2.7 \
+                zlib1g \
+                bzip2 \
+                libxml2 \
+                libicu60 \
+          "
     _boost_requires_list=$(echo ${_boost_requires} | tr ' ' ',')
     # _boost_conflicts_list=""
-    ###	     --conflicts="${_boost_conflicts_list}" 
-    echo >&2 "[info] Requires : ${_boost_requires_list}!"	
+    ###      --conflicts="${_boost_conflicts_list}" 
+    echo >&2 "[info] Requires : ${_boost_requires_list}!"       
     if [ ${_boost_do_package} == true ]; then
-	if [ "x${os_arch}" != "xx86_64" ]; then
-	    echo >&2 "[error] Unsupported architecture ${os_arch}!"	
-	    return 1
-	fi
-	sudo checkinstall \
-	     --type="debian" \
-	     --install="no" \
-	     --fstrans="no" \
-	     --pkgname="bx${package_name}" \
-	     --pkgversion="${package_version}" \
-	     --pkgrelease=${pkg_release} \
-	     --pkglicense="Boost Software License" \
-	     --pkgsource="$(boost_installer_get_url ${package_version})" \
-	     --maintainer="${pkg_maintener_email}" \
-	     --provides="bx${package_name}" \
-	     --requires="${_boost_requires_list}" \
-	     --backup="no" \
-	     --pakdir="${package_dir}" \
-	     --default \
-	     ninja install
-	if [ $? -ne 0 ]; then
-	    echo >&2 "[error] Debian binary package build failed!"	
-	    return 1
-	fi
-    fi	 
+        if [ "x${os_arch}" != "xx86_64" ]; then
+            echo >&2 "[error] Unsupported architecture ${os_arch}!"     
+            return 1
+        fi
+        sudo checkinstall \
+             --type="debian" \
+             --install="no" \
+             --fstrans="no" \
+             --pkgname="bx${package_name}" \
+             --pkgversion="${package_version}" \
+             --pkgrelease=${pkg_release} \
+             --pkglicense="Boost Software License" \
+             --pkgsource="$(boost_installer_get_url ${package_version})" \
+             --maintainer="${pkg_maintener_email}" \
+             --provides="bx${package_name}" \
+             --requires="${_boost_requires_list}" \
+             --backup="no" \
+             --pakdir="${package_dir}" \
+             --default \
+             ninja install
+        if [ $? -ne 0 ]; then
+            echo >&2 "[error] Debian binary package build failed!"      
+            return 1
+        fi
+    fi   
     return 0
 }
 
@@ -463,10 +463,10 @@ function boost_installer_setup()
     local _bxsoftware_setup_script="${_bxsoftware_setup_dir}/${bxiw_package_name}.bash"
     bxiw_message "info" "Installing setup script '${_bxsoftware_setup_script}'..."
     cat ${bxiw_app_installer_prefix}/resources/${bxiw_package_name}.bash.in | \
-	sed \
-	    -e "s@__BOOST_INSTALL_DIR__@${bxiw_install_dir}@g" \
-	    -e "s@__BOOST_VERSION__@${bxiw_package_version}@g" \
-	    > ${_bxsoftware_setup_script}
+        sed \
+            -e "s@__BOOST_INSTALL_DIR__@${bxiw_install_dir}@g" \
+            -e "s@__BOOST_VERSION__@${bxiw_package_version}@g" \
+            > ${_bxsoftware_setup_script}
     return  0
 }
 
@@ -510,7 +510,7 @@ fi
 if [ ${bxiw_with_package} == false ]; then
     boost_installer_setup
     if [ $? -ne 0 ]; then
-	bxiw_exit 1 "Setup failed!"
+        bxiw_exit 1 "Setup failed!"
     fi
 fi
 
