Update installers

diff --git a/BxBayeuxInstaller/bayeux_installer b/BxBayeuxInstaller/bayeux_installer
--- a/BxBayeuxInstaller/bayeux_installer
+++ b/BxBayeuxInstaller/bayeux_installer
@@ -265,7 +265,16 @@ function bayeux_installer_prepare()
 	fi
     fi
 
-    # Boost:
+    # Prepare:
+    _bxiw_prepare_post
+
+    return 0
+}
+
+  
+function bayeux_check_dependencies()
+{
+ # Boost:
     if [ ${bayeux_no_system_boost} == true ]; then
 	if [ "x${bayeux_boost_root}" = "x" ]; then
 	    if [ "x${BX_BOOST_INSTALL_DIR}" != "x" ]; then
@@ -341,14 +350,16 @@ function bayeux_installer_prepare()
 	else               
 	   bayeux_camp_dir="/usr/lib/x86_64-linux-gnu/cmake/camp"
 	fi
-	if [ "x${bayeux_camp_dir}" = "x" ]; then
-	    if [ "x${bayeux_camp_prefix}" != "x" ]; then
-		if [ ! -d ${bayeux_camp_prefix} ]; then
-		    bxiw_log_error "CAMP installation directory '${bayeux_camp_prefix}' does not exist!"
-		    return 1
+	if [ ${bayeux_no_system_camp} == true ]; then
+	    if [ "x${bayeux_camp_dir}" = "x" ]; then
+		if [ "x${bayeux_camp_prefix}" != "x" ]; then
+		    if [ ! -d ${bayeux_camp_prefix} ]; then
+			bxiw_log_error "CAMP installation directory '${bayeux_camp_prefix}' does not exist!"
+			return 1
+		    fi
 		fi
+		bayeux_camp_dir="${bayeux_camp_prefix}/lib/camp/cmake"
 	    fi
-	    bayeux_camp_dir="${bayeux_camp_prefix}/lib/camp/cmake"
 	fi
     else
 	bxiw_log_info "CAMP dir='${bayeux_camp_dir}'"
@@ -592,6 +603,7 @@ function bayeux_installer_get_url()
 
 function bayeux_installer_set_system_dependencies()
 {
+    # echo >&2 "====> bayeux_installer_set_system_dependencies : Entering"
     if [[ "x${bxiw_os_distrib_id}" = "xUbuntu" || "x${bxiw_os_distrib_id}" = "xLinuxMint" ]]; then
 	bxiw_system_packages_build="cmake \
    	  	    ninja-build \
@@ -659,12 +671,18 @@ function bayeux_installer_set_system_dependencies()
 	    bxiw_system_packages_build="${bxiw_system_packages_build} libxerces-c-dev"
 	    bxiw_system_packages_build="${bxiw_system_packages_build} libcamp-dev"
 	fi
+	if [ "x${bxiw_os_distrib_release}" = "x22.04" ]; then
+	    bxiw_system_packages_build="${bxiw_system_packages_build} libxerces-c-dev"
+	    bxiw_system_packages_build="${bxiw_system_packages_build} libcamp-dev"
+	fi
+	# echo >&2 "====> bxiw_system_packages_build=${bxiw_system_packages_build}"
 	bxiw_pass
     elif [ "x${bxiw_os_distrib_id}" = "xCentOS" ]; then
 	bxiw_pass
     elif [ "x${bxiw_os_distrib_id}" = "xScientific" ]; then
 	bxiw_pass
     fi
+    # echo >&2 "====> bxiw_system_packages_build=${bxiw_system_packages_build}"
     bxiw_system_packages_run="${bxiw_system_packages_build}"
     return 0
 }
@@ -948,10 +966,9 @@ function bayeux_installer_install()
 	    local _werror="OFF"
 	fi
 
-        local _cxx_std_option="-DCMAKE_CXX_STANDARD=${bayeux_cxx_std}"
-	
-	echo >&2 "[info] bayeux_with_werror=${bayeux_with_werror}"
-	echo >&2 "[info] _werror=${_werror}"
+        local _cxx_std_option="-DCMAKE_CXX_STANDARD=${bayeux_cxx_std}"	
+	# echo >&2 "[info] bayeux_with_werror=${bayeux_with_werror}"
+	# echo >&2 "[info] _werror=${_werror}"
 	cmake \
 	    -DCMAKE_BUILD_TYPE:STRING="Release" \
  	    -DCMAKE_INSTALL_PREFIX:PATH="${bxiw_install_dir}" \
@@ -1189,12 +1206,15 @@ if [ $? -ne 0 ]; then
     bxiw_exit 1 "Command line parse error!"
 fi
 
+# echo >&2 "====> calling bayeux_installer_prepare..."
+
 bayeux_installer_prepare
 if [ $? -ne 0 ]; then
     bxiw_exit 1 "Preparation failed!"
 fi
 
 # bxiw_exit 1
+# echo >&2 "====> calling bayeux_installer_set_system_dependencies..."
 
 bayeux_installer_set_system_dependencies
 
@@ -1205,19 +1225,20 @@ if [ $? -ne 0 ]; then
     bxiw_exit 1 "System dependencies installation failed!"
 fi
 
+bayeux_check_dependencies
+if [ $? -ne 0 ]; then
+    bxiw_exit 1 "Dependency checks failed!"
+fi
+
 bayeux_installer_download
 if [ $? -ne 0 ]; then
     bxiw_exit 1 "Source archive download failed!"
 fi
 
-# bxiw_exit 0
-
 bayeux_installer_install
 if [ $? -ne 0 ]; then
     bxiw_exit 1 "Installation failed!"
 fi
-
-# bxiw_exit 0
 
 if [ ${bxiw_with_package} == false ]; then
     bayeux_installer_setup
